name: 'Terraform Destroy'

on:
  push:
    branches:
    - main
         

jobs:
  terraform:
    name: 'Dev Pipeline - Panorama Deployment'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      #working-directory: ./terraform/panorama
      run: terraform init
      env:
        TF_WORKSPACE: "dev"
    
    - name: Terraform Workspace
      id: workspace
      #working-directory: ./terraform/panorama
      run: terraform workspace select dev
        
    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve
